### ISSUE TITLE
Feature request: make Theme Breakpoint JS an optional dependency

### ISSUE THREAD

**Issue by dmsmidt** [BurdaMagazinOrg/module-ad_entity#13]
Thanks for your contributions to the Drupal ecosystem.

We are using your module in one of our sites.
Currently you always need to install the Theme Breakpoint JS module even if you don't want to change ads per breakpoint.
Could this be made optional please in order to keep a smaller footprint?

**Comment by mxhCodes** [comment]
I understand your point and will do some further analysis on this. If it's no big hassle I'm gonna change it. If you want to push things forward, feel free to contribute and create a PR here or create an issue on drupal.org.

**Comment by mxhCodes** [comment]
I looked into the module code in detail and came to the conclusion that it doesn't proportionally make sense to decouple the module from theme_breakpoints_js. We'd need to implement fallbacks and often need to check whether the module exists for using it, as many configurations and logic depend on the results provided by this module.

Are there any arguments, besides from having one hard dependency less, which would justify a decoupled solution?

**Comment by mxhCodes** [comment]
Theme Breakpoints JS is now optional since 1.0-beta17.

**Comment by dmsmidt** [comment]
Great thanks for your work on this.
