### ISSUE TITLE
Show different Ads in the same block at different pages

### ISSUE THREAD

**Issue by milkovsky** [BurdaMagazinOrg/module-ad_entity#20]
Let's assume:
-  there are next channels(taxonomy vocabulary in Thunder): A, B, C.
-  there is one "Ad unit" (in DFP) per taxonomy term (channel): Unit A, Unit B, Unit C.
-  An ad should be shown in header depending on taxonomy term context.

In this case I want to show an advertisement from different "Ads units" (DFP) in the same header block.

In this case I would need some Ad factory service, which delivers Ad display depending on Ads placement type(header/footer) and page context (channel name in our case)

Is it possible to do it with this module right now?

**Comment by mxhCodes** [comment]
Does each term have its own ad unit? You could create some fields on the terms, which hold the necessary information, and manipulate the values of a "standard" Advertising entity configuration by implementing `hook_ad_entity_view_alter`.

**Comment by milkovsky** [comment]
Sounds good, thanks!

**Comment by milkovsky** [comment]
works for me. I have added a small custom service, which get's the top-parent channel term from url for nodes, terms pages.
I use it in the hook_ad_entity_view_alter.
