### ISSUE TITLE
DFP: Ads are showing up after Ad Units have been disabled

### ISSUE THREAD

**Issue by jintnc** [BurdaMagazinOrg/module-ad_entity#24]
Hi!
After deactivating all Ad Units and Line Items on Doubleclick which were associated with our D8 site, Ads from various Ad agencies like criteo are showing up. 
I am still wondering whether it is a Doubleclick issue or caused by this module.
Does anyone have an idea?

**Comment by milkovsky** [comment]
I can confirm this issue. The ad unit is disabled.
That's weird. We have added embedded the Ad 2 times:
- 1st time with the ad_entity module
- and 2nd by adding the js code manually into a block.
The 2nd (custom) block did not show any ad. 
But some random advertisement appeared in the 1st (ad_entity) block.

Does the module add some Ad fallback?

**Comment by mxhCodes** [comment]
> Does the module add some Ad fallback?

no

Please provide more details. Post your custom code which behaves correctly.

For a quick solution, you could disable the ads with the help of site-wide context via /admin/structure/ad_entity/global-settings

**Comment by milkovsky** [comment]
@mxhaupt , thank you for the feedback. I have checked the code and did not find any issue there.
I will provide more details once I can reproduce the issue again. Al the Ads are now magically gone.

**Comment by milkovsky** [comment]
@mxhaupt we reproduced it. It happens when you create a disabled new ad_unit / rename the old one.

**Comment by milkovsky** [comment]
Or enter a name of a non-existing ad-unit.

**Comment by milkovsky** [comment]
We think, that there is a fallback configured in DFP settings. We will check it on Monday. Have a nice weekend!

**Comment by mxhCodes** [comment]
Thanks, you too

**Comment by mxhCodes** [comment]
Assuming this is fixed. Feel free to reopen if not.

**Comment by milkovsky** [comment]
Yes. it is fixed. There is indeed a fallback setting in DFP.
