### ISSUE TITLE
Number of device variants insufficient

### ISSUE THREAD

**Issue by mxhaupt** [BurdaMagazinOrg/module-ad_entity#3]
The current set of the device variants "smartphone", "tablet" and "desktop" are insufficient for many projects. We need to implement a new approach for this.
Suggestions:

1. Extend the Breakpoint JS settings module in the way that you're able to define and map to your own device types (number of types is unlimited).  The ad_entity module must then be extended in the way that it fetches the user-defined device mappings. For being backwards-compatible, the Breakpoint JS settings module could just provide a pre-defined set of device types (smartphone, tablet, desktop).
2. Let ad_entity not use Breakpoint JS settings device mappings at all. Directly use any available, non-empty breakpoint. The downside of this is that you may have a large number of breakpoints to setup on each Advertising block.
3. The logic described in suggestion 1, being completely moved to ad_entity. It could be exposed as global settings in the section for managing advertsing entities. This would make the ad_entity module independent from the Breakpoint JS settings module. Advantage is that ad_entity can be more flexible and faster adapted for more complex requirements. Disadvantage would be possible feature and code duplication, e.g. when another module needs a similar or the same model for device types being mapped to breakpoints.

**Comment by mxhCodes** [comment]
This issue has been solved since 1.0-alpha7.
